// src/components/CrudTableBtnAdd/CrudTableBtnAdd.vue
<template>
   <el-button :icon="Plus" type="primary" @click="onBtnClick" v-bind="$attrs">
      {{ props.text }}
   </el-button>
</template>

<script setup lang="ts">
import { Plus } from '@element-plus/icons-vue';
import { TYPE_ADD } from '../../token';
import { useEventDispatcher } from '../../hooks';

const props = defineProps({
   text: {
      type: String,
      default: '新增'
   },
   url: String,
   dialogTitle: {
      type: String,
      default: '新增'
   }
});

const dispatch = useEventDispatcher();
const onBtnClick = () => {
   dispatch('showDialog', {
      type: TYPE_ADD,
      title: props.dialogTitle,
      url: props.url
   });
};
</script>

// src/components/CrudTableBtnAdd/CrudTableBtnAdd.tsx
import { Plus } from '@element-plus/icons-vue'
import { ACTION__SHOW_DIALOG, TYPE_ADD } from '../../token'
import { CrudTableBtnOpts } from '../../types'
import { useDispatchAction } from '../../hooks'


function CrudTableBtnAdd(props: CrudTableBtnOpts) {
  const {text = '新增', dialogTitle = '新增', url, ...rest} = props
  const showDialog = useDispatchAction(ACTION__SHOW_DIALOG, {
    type: TYPE_ADD,
    title: dialogTitle,
    url
  })
  return (
    <el-button
      icon={ Plus }
      type="primary"
      { ...rest }
      onClick={ showDialog }>
      { text }
    </el-button>
  )
}

export default CrudTableBtnAdd
